### ISSUE TITLE
Entering a 4 digit error input in the prompts will lead to an error

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/assembly-calculator#10]
**Describe the bug**
Entering a 4 digit that leads to an error input in the prompts will lead to a bug, and will not let the user re-enter their inputs and will cause the program to crash.
![entering 4 digits in the prompt will show the error](https://user-images.githubusercontent.com/99312804/181879732-48796bd4-4b59-4246-a1b9-11b765993926.JPG)
![4digitsex2](https://user-images.githubusercontent.com/99312804/181879733-fc112f7f-a65c-4a5e-b243-b4f280228c2b.JPG)

 
**To Reproduce**
1. Go to any prompts
2. Enter a 4 digit that leads to an error input 
3. See error

**Expected behavior**
It should let user re-enter the inputs

**Comment by BeepBoopBit** [comment]
It does let the user re-input. the problem is that, the character in the terminal doesn't get removed. The error that you see is the result of not inputting any data rather than 4-digit error
