### ISSUE TITLE
Subtraction using number 257 and above on the first number input results to incorrect output if second number input is lower

### ISSUE THREAD

**Issue by paulreonal** [BeepBoopBit/assembly-calculator#11]
**Describe the bug**
Subtraction using numbers starting from 257 and above has an error if the first number input (257 - 999) is larger than the second number input (0 - 256). 

**To Reproduce**
1. Start using numbers from 257 to 999 ( try 257)
2. Subtract it to a lower value (try 1)
3. Output is 0

**Expected behavior**
257 - 1 = 256

**Comment by BeepBoopBit** [comment]
Fix at 6e44e1553414f22a5069e37c8ba9b344e41bb3af
