### ISSUE TITLE
Division with 0 as the second number will lead to an error 

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/assembly-calculator#12]
**Describe the bug**
Division with 0 as the second number input will lead to an error in the program
![Divsion with 0 will lead to an error](https://user-images.githubusercontent.com/99312804/181879990-898caae3-1f0d-4160-a2e3-104cfb3198ac.JPG)

**To Reproduce**
1. Go to second number prompt
2. Enter a zero and division as the operator
3. See error

**Expected behavior**
Should print the results

**Comment by BeepBoopBit** [comment]
Fix at 16d695758ca94a5b8de61050d68a40332bf9e437
