### ISSUE TITLE
7777 does not multiply with numbers 9 and above, 8888 does not multiply with numbers 8 and above, 9999 does not multiply with numbers 7 and above

### ISSUE THREAD

**Issue by paulreonal** [BeepBoopBit/assembly-calculator#13]
**Describe the bug**
5555 does not multiply with numbers 11 and above (11-9999), 6666 does not multiply with numbers 10 and above (10-9999), 7777 does not multiply with numbers 9 and above (9-9999), 8888 does not multiply with numbers 8 and above (8-9999), 9999 does not multiply with numbers 7 and above (7-9999)

**To Reproduce**
1. Input 7777 (can be first or second)
2. Input  9
3. Output is 4457

**Expected behavior**
7777*9 = 69993

**Comment by BeepBoopBit** [comment]
The calculator only support storing and calculating of data in range of  **0-FFFF**
