### ISSUE TITLE
If the input of the user in the second number is either (1) or (2) digits. The results of the division would always result in inf

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/assembly-calculator#19]
**Describe the bug**
If the input of the user in the second number is either (1) or (2) digits. The results of the division would always result in infinite. I have tested inputting three and four digits in the second number and the program would work properly. 
![inf1](https://user-images.githubusercontent.com/99312804/182106366-47e9b750-9cca-4d7e-9bb5-673425ae20fd.JPG)
![inf2](https://user-images.githubusercontent.com/99312804/182106047-410f0cba-44b6-45e9-aecd-14ef5b04f1ad.JPG)
d87.JPG)
![inf3](https://user-images.githubusercontent.com/99312804/182106058-6f95b56d-a2bf-416a-ba53-ab71a64ff6db.JPG)
![inf4](https://user-images.githubusercontent.com/99312804/182106091-ce47e663-7e5a-4749-9bb5-22584e9d711d.JPG)
![inf5](https://user-images.githubusercontent.com/99312804/182106107-d596433c-45d7-4934-9293-0b161d665b34.JPG)

**To Reproduce**
1. Enter any value in the first number
2. Click on the second value and insert either (1) or (2) digits of number
3. See the result as inf

**Expected behavior**
it should not result in inf

**Comment by BeepBoopBit** [comment]
Resolve at: 6d4acb7050c97eded0a0887d8398f327226c534b
