### ISSUE TITLE
Cannot input anything that is wrong 

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/assembly-calculator#4]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: 'braie'

---

**Describe the bug**
The program does not let the user input anything that is wrong.
For the numbers, the program does not accept a character as an input. It would not read anything if it is not an integer.
For the operations, it would not accept anything that is not '+'  '-'  '*'  '/'.

**To Reproduce**
1. Go to 'the input of character and operations'
2. Try to put some wrong inputs
3. See error

**Expected behavior**
It should still accept wrong inputs and tell user that their input is wrong.

**Screenshots**
![meme](https://user-images.githubusercontent.com/99312804/179770149-bffdf13d-a0b2-4a8c-afb3-12935651d3d4.JPG)

**Additional context**

**Comment by BeepBoopBit** [comment]
Check again if the Problem have been resolve

**Comment by braiee** [comment]
resolved
