### ISSUE TITLE
Entering any value in exit prompt does not clear the screen

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/assembly-calculator#9]
**Describe the bug**
Entering aby value in the exit prompt does not clear the screen
![Enterting an integer does not clear the screen](https://user-images.githubusercontent.com/99312804/181879427-dce4cd17-a42e-4ff4-9899-d23910429683.JPG)
![clearthe screen](https://user-images.githubusercontent.com/99312804/181879431-8a916231-e166-4623-92aa-74de65c7384e.JPG)

**To Reproduce**
1. Go to exit prompt
2. Enter any value
3. See error

**Expected behavior**
Should clear the screen

**Comment by BeepBoopBit** [comment]
Fix at ee5d405f51c3ad514563cb34cf77c290ec9d8792
